-- =========================
-- Migration V9 pour H2 (tests)
-- Ajout des champs d'authentification et d'administration
-- =========================

-- Ajout du champ d'administration pour les employés
ALTER TABLE EMPLOYE 
    ADD COLUMN IF NOT EXISTS ADMIN_PRIVILEGE BOOLEAN DEFAULT FALSE;

-- Ajout des champs d'authentification pour EMPLOYE
ALTER TABLE EMPLOYE
    ADD COLUMN IF NOT EXISTS NOM_UTILISATEUR VARCHAR(255),
    ADD COLUMN IF NOT EXISTS EMAIL_AUTH VARCHAR(255),
    ADD COLUMN IF NOT EXISTS MOT_DE_PASSE VARCHAR(255) NOT NULL;

-- Contraintes uniques pour H2
ALTER TABLE EMPLOYE
    ADD CONSTRAINT IF NOT EXISTS UC_EMPLOYE_EMAIL_AUTH UNIQUE (EMAIL_AUTH);

-- Ajout des champs d'authentification pour CITOYEN
ALTER TABLE CITOYEN
    ADD COLUMN IF NOT EXISTS NOM_UTILISATEUR VARCHAR(255),
    ADD COLUMN IF NOT EXISTS EMAIL_AUTH VARCHAR(255);

ALTER TABLE CITOYEN
    ADD CONSTRAINT IF NOT EXISTS UC_CITOYEN_EMAIL_AUTH UNIQUE (EMAIL_AUTH);

-- Ajout des champs d'authentification pour TECHNICIEN
ALTER TABLE TECHNICIEN
    ADD COLUMN IF NOT EXISTS NOM_UTILISATEUR VARCHAR(255),
    ADD COLUMN IF NOT EXISTS EMAIL_AUTH VARCHAR(255),
    ADD COLUMN IF NOT EXISTS MOT_DE_PASSE VARCHAR(255) NOT NULL;

ALTER TABLE TECHNICIEN
    ADD CONSTRAINT IF NOT EXISTS UC_TECHNICIEN_EMAIL_AUTH UNIQUE (EMAIL_AUTH);
